#!/usr/bin/env ruby

require 'rubygems'
require 'net/http'
require 'json'

DEFAULT_HOST = 'http://127.0.0.1:3000'
CONFIG_PATH = File.expand_path('~/.pjr')

def default_host
  if File.exist?(CONFIG_PATH) &&
      File.read(CONFIG_PATH) =~ /default_host:(.+)/i
    $1.strip
  else
    DEFAULT_HOST
  end
end

def process_url(url, options)
  if url !~ /\Ahttp/
    url = '/' + url unless url.start_with?('/')
    url = default_host + url
  end

  puts "Retrieving #{url}:"

  resp = Net::HTTP.get_response(URI.parse(url))
  data = JSON.parse(resp.body)
  if options['irb']
    require 'irb'
    @response = data
    puts "Loading IRB."
    puts "JSON response is in @response"
    IRB.start
  else
    puts JSON.pretty_unparse(data)    
  end
end

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: pjr [options] <uri>"
  opts.separator "Specific options:"

  opts.on("-i", "Dump the results into @response in IRB") do
    options['irb'] = true
  end
  
  opts.on_tail("-h", "Show this message") do
    puts opts
    exit
  end
end.parse!

process_url ARGV.shift, options
